id: P876ABC00
initial_creation_type: ocr
source_metadata:
  volumes:
    29af59204b3b41b48aba272ce4e3152b:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: གནོད་སྦྱིན་གྱི་སྡེ་དཔོན་ཆེན་པོ་ལག་ན་རྡོ་རྗེ་གོས་སྔོན་པོ་ཅན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1464
      volume_number: 47
